export const heros = [
  {
    id: "1",
    superhero: "spider-man",
    publisher: "Marvel Comics",
    alter_ego: "Peter Parker",
    first_appearance: "Amazing Fantasy #15",
    characters: "Peter Parker",
  },
  {
    id: "2",
    superhero: "captain-america",
    publisher: "Marvel Comics",
    alter_ego: "Steve Rogers",
    first_appearance: "Captain America Comics #1",
    characters: "Steve Rogers",
  },
  {
    id: "3",
    superhero: "iron-man",
    publisher: "Marvel Comics",
    alter_ego: "Tony Stark",
    first_appearance: "Tales of Suspense #39",
    characters: "Tony Stark",
  },
  {
    id: "4",
    superhero: "thor",
    publisher: "Marvel Comics",
    alter_ego: "Thor Odinson",
    first_appearance: "Journey into Myster #83",
    characters: "Thor Odinson",
  },
  {
    id: "5",
    superhero: "hulk",
    publisher: "Marvel Comics",
    alter_ego: "Bruce Banner",
    first_appearance: "The Incredible Hulk #1",
    characters: "Bruce Banner",
  },
  {
    id: "6",
    superhero: "wolverine",
    publisher: "Marvel Comics",
    alter_ego: "James Howlett",
    first_appearance: "The Incredible Hulk #180",
    characters: "James Howlett",
  },
  {
    id: "7",
    superhero: "daredevil",
    publisher: "Marvel Comics",
    alter_ego: "Matthew Michael Murdock",
    first_appearance: "Daredevil #1",
    characters: "Matthew Michael Murdock",
  },
  {
    id: "8",
    superhero: "hawkeye",
    publisher: "Marvel Comics",
    alter_ego: "Clinton Francis Barton",
    first_appearance: "Tales of Suspense #57",
    characters: "Clinton Francis Barton",
  },
  {
    id: "9",
    superhero: "cyclops",
    publisher: "Marvel Comics",
    alter_ego: "Scott Summers",
    first_appearance: "X-Men #1",
    characters: "Scott Summers",
  },
  {
    id: "10",
    superhero: "silver-surfer",
    publisher: "Marvel Comics",
    alter_ego: "Norrin Radd",
    first_appearance: "The Fantastic Four #48",
    characters: "Norrin Radd",
  },
];

// export const heros = [
//   {
//       id: "0",
//     name: "Captain America",
//     realname: "Steve Rogers",
//     team: "Avengers",
//     firstappearance: "1941",
//     createdby: "Joe Simon",
//     publisher: "Marvel Comics",
//     imageurl: "https://www.simplifiedcoding.net/demos/marvel/captainamerica.jpg",
//   },
//   {
//       id: "1",
//     name: "Iron Man",
//     realname: "Tony Stark",
//     team: "Avengers",
//     firstappearance: "1963",
//     createdby: "Stan Lee",
//     publisher: "Marvel Comics",
//     imageurl: "https://www.simplifiedcoding.net/demos/marvel/ironman.jpg",
//   },
//   {
//       id: "2",
//     name: "Wolvarine",
//     realname: "James Howlett",
//     team: "X-Men",
//     firstappearance: "1974",
//     createdby: "Len Wein",
//     publisher: "Marvel Comics",
//     imageurl: "https://www.simplifiedcoding.net/demos/marvel/logan.jpg",
//   },
//   {
//       id: "3",
//     name: "Spiderman",
//     realname: "Peter Parker",
//     team: "Avengers",
//     firstappearance: "1962",
//     createdby: "Stan Lee",
//     publisher: "Marvel Comics",
//     imageurl: "https://www.simplifiedcoding.net/demos/marvel/spiderman.jpg",
//   },
//   {
//       id: "4",
//     name: "Thor",
//     realname: "Thor Odinson",
//     team: "Avengers",
//     firstappearance: "1962",
//     createdby: "Stan Lee",
//     publisher: "Marvel Comics",
//     imageurl: "https://www.simplifiedcoding.net/demos/marvel/thor.jpg",
//   },
// ];
